spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/gym_management_system
#    username: root
#    password: 12345678
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres?currentSchema=traffic_data
    username: test
    password: test@123456
  thymeleaf:
    cache: false


#server:
#  port: 8888

mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.milotnt.pojo